# Generated by Django 5.2.3 on 2025-08-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0006_alter_users_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
    ]
