# Generated by Django 5.2.3 on 2025-08-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': (('admin_perm', 'admin can take complaints'),)},
        ),
    ]
