# Generated by Django 5.2.3 on 2025-08-30 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminArea',
            new_name='AdminForLocation',
        ),
    ]
