# Generated by Django 5.2.3 on 2025-08-30 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_adminarea_adminforlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminForLocation',
            new_name='complaints_handler',
        ),
    ]
