# Generated by Django 5.2.3 on 2025-08-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_votes_complaintvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
