# Generated by Django 5.2.3 on 2025-08-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='slug',
        ),
    ]
